"""A small curated seed of prose/law questions, hand-authored from real KB units.

These exist so the review queue and the player have genuine multi-theme content
before anyone runs the LLM drafter (`run.py draft`), and so the
review→approve→publish loop is demonstrable end-to-end. They are *drafts like any
other*: loaded through the same grounding + validation path and stored as
`pending` (generator `seed:curated.v1`) — a human must still approve them.

Each entry is keyed by a KB unit `ref`; the loader (`prose.seed_questions`)
attaches that unit's provenance/licence and grounds the answer against its text.
Choices are (text, is_correct).
"""

SEED = [
    # --- Définitions (ONI art. 2) -------------------------------------------
    {"ref": "ONI art. 2", "polarity": "affirmative",
     "stem": "Au sens de l’ONI, que désigne le terme « bateau motorisé » ?",
     "choices": [("Un bateau à propulsion mécanique", True),
                 ("Un bateau non propulsé remorqué par un autre bateau", False),
                 ("Un engin flottant tel qu’une drague ou une grue", False)],
     "explanation": "ONI art. 2 : le « bateau motorisé » est un bateau à propulsion mécanique."},
    {"ref": "ONI art. 2", "polarity": "affirmative",
     "stem": "Qu’est-ce qu’un « convoi poussé » selon l’ONI ?",
     "choices": [("Une composition de bateaux non propulsés réunis en un ensemble rigide, poussée par au moins un bateau à moteur", True),
                 ("Une composition de bateaux non propulsés remorquée par au moins un bateau à moteur", False),
                 ("Tout groupe de bateaux de plaisance naviguant ensemble", False)],
     "explanation": "ONI art. 2 : le convoi poussé est un ensemble rigide poussé ; remorqué = convoi remorqué."},

    # --- Météorologie (MétéoSuisse : La bise) -------------------------------
    {"ref": "MétéoSuisse : La bise", "polarity": "affirmative",
     "stem": "De quelle direction souffle la bise sur le Petit-Lac et le Grand-Lac ?",
     "choices": [("Du nord-est (NE)", True),
                 ("Du sud-ouest (SO)", False),
                 ("Du nord-ouest sur l’ensemble du lac", False)],
     "explanation": "MétéoSuisse : la bise souffle du NE sur le Petit et le Grand-Lac (NNW seulement sur le Haut-Lac)."},
    {"ref": "MétéoSuisse : La bise", "polarity": "affirmative",
     "stem": "À quelle période la bise est-elle nettement dominante sur le Léman ?",
     "choices": [("Dans la première moitié de l’année, notamment au printemps", True),
                 ("En plein été, de juillet à août", False),
                 ("Uniquement lors des nuits d’automne", False)],
     "explanation": "MétéoSuisse : la bise est dominante dans la première moitié de l’année, surtout au printemps."},

    # --- Matelotage (Nœud de chaise) ----------------------------------------
    {"ref": "Matelotage — Nœud de chaise : Roi des nœuds", "polarity": "affirmative",
     "stem": "Pourquoi le nœud de chaise est-il qualifié de « roi des nœuds » ?",
     "choices": [("C’est un nœud de boucle fiable qui ne glisse pas sous tension et se dénoue facilement", True),
                 ("Il se resserre de plus en plus sous tension jusqu’à devenir indénouable", False),
                 ("Il sert uniquement à raccorder deux cordages de même diamètre", False)],
     "explanation": "Le nœud de chaise est une boucle fiable qui ne glisse pas et se dénoue aisément."},
    # (Dropped on review: a "how many teaching methods exist for the bowline?"
    #  item — grounded in the WP text but pure trivia, no exam relevance.)

    # --- Eaux frontalières (RNL art. 64 — Priorités) ------------------------
    {"ref": "RNL art. 64", "polarity": "affirmative",
     "stem": "Face à un bateau incapable de manœuvrer qui signale sa présence, que doit faire tout autre bateau ?",
     "choices": [("S’écarter de ce bateau", True),
                 ("Maintenir son cap et sa vitesse", False),
                 ("Le dépasser par tribord", False)],
     "explanation": "RNL art. 64, al. 1 : tout bateau doit s’écarter d’un bateau incapable de manœuvrer qui signale sa présence."},
    {"ref": "RNL art. 64", "polarity": "affirmative",
     "stem": "En cas de rencontre, de quels bateaux tout bateau — hormis les bateaux à passagers prioritaires et les convois remorqués — doit-il s’écarter ?",
     "choices": [("Des bateaux à marchandises", True),
                 ("Des bateaux de plaisance", False),
                 ("Des bateaux de sport naviguant à la voile", False)],
     "explanation": "RNL art. 64, al. 2 let. b : il s’écarte des bateaux à marchandises."},

    # --- Lois (ONI art. 134 — Engins de sauvetage) --------------------------
    {"ref": "ONI art. 134", "polarity": "affirmative",
     "stem": "Lesquels de ces engins sont des moyens de sauvetage INDIVIDUELS au sens de l’ONI ?",
     "choices": [("Les gilets de sauvetage avec cols", True),
                 ("Les bouées de sauvetage", True),
                 ("Les îlots de sauvetage pour l’embarquement", False)],
     "explanation": "ONI art. 134 : gilets avec cols et bouées = individuels ; les îlots d’embarquement sont collectifs."},
    {"ref": "ONI art. 134", "polarity": "affirmative",
     "stem": "Quelle poussée hydrostatique minimale un moyen de sauvetage individuel doit-il avoir (cas général) ?",
     "choices": [("Au moins 75 N", True),
                 ("Au moins 750 N", False),
                 ("Au moins 50 N", False)],
     "explanation": "ONI art. 134, al. 2 : au moins 75 N (sauf bateaux visés à l’art. 134a)."},

    # --- Voile (cat-D, étude — non examiné en théorie) ----------------------
    # Grounded in the FR Wikipedia "voile" KB units (CC BY-SA). Sailing technique
    # is NOT on the theory exam (identical for cat-A/D); these surface as study
    # content for the cat-D practical. Answers use the source's own vocabulary so
    # the grounding check passes; one human still approves them via `review`.
    {"ref": "Voile — Allure (marine) : Le vent debout", "polarity": "affirmative",
     "stem": "À l’allure du vent debout, que doit faire le voilier pour pouvoir progresser à l’aide de ses voiles ?",
     "choices": [("S’écarter d’environ 45° de l’axe du vent (30° sur les voiliers de régate les plus performants)", True),
                 ("Maintenir son cap exactement face au vent en bordant ses voiles au maximum", False),
                 ("Établir le spinnaker pour capter le vent venant de l’avant", False)],
     "explanation": "Face au vent (vent debout) le voilier ne peut pas avancer : il doit s’écarter d’environ 45° de l’axe du vent (30° en régate) et louvoyer."},
    {"ref": "Voile — Allure (marine) : Tribord amures, bâbord amures", "polarity": "affirmative",
     "stem": "Quand dit-on qu’un voilier est « tribord amures » ?",
     "choices": [("Lorsque le vent vient de la droite par rapport à l’axe du navire", True),
                 ("Lorsqu’il navigue vent arrière, les voiles en ciseaux", False),
                 ("Lorsqu’il a la priorité sur tous les autres bateaux du plan d’eau", False)],
     "explanation": "Le voilier est tribord amures quand le vent vient de la droite (tribord) ; bâbord amures dans le cas inverse. Ces distinctions fondent les règles de priorité entre voiliers."},
    {"ref": "Voile — Allure (marine) : Le vent arrière", "polarity": "affirmative",
     "stem": "Qu’observe-t-on à l’allure du vent arrière ?",
     "choices": [("Le roulis s’accentue et l’empannage menace", True),
                 ("La vitesse devient maximale, supérieure à celle du grand largue", False),
                 ("Le voilier ne peut plus avancer car il est face au vent", False)],
     "explanation": "Au vent arrière l’écoulement de l’air est perturbé : la vitesse diminue par rapport au grand largue, le roulis s’accentue et l’empannage menace."},
    {"ref": "Voile — Virement de bord : Principe", "polarity": "affirmative",
     "stem": "Que se passe-t-il lors d’un virement de bord ?",
     "choices": [("Le côté du bateau qui était sous le vent passe au vent, et vice-versa", True),
                 ("Le voilier conserve la même amure tout au long de la manœuvre", False),
                 ("La manœuvre se fait obligatoirement en passant par le vent arrière", False)],
     "explanation": "Au virement de bord, le côté qui était sous le vent passe au vent (changement d’amure par le vent debout)."},
    {"ref": "Voile — Empannage : Définition", "polarity": "affirmative",
     "stem": "Qu’est-ce qui caractérise l’empannage par rapport au virement de bord ?",
     "choices": [("Le changement d’amure se fait en passant par le vent arrière", True),
                 ("Le changement d’amure se fait en passant par le vent debout", False),
                 ("Il ne modifie pas l’orientation des voiles", False)],
     "explanation": "L’empannage change d’amure en passant par le vent arrière ; passer par le vent debout est au contraire un virement de bord."},
    {"ref": "Voile — Chavirage : Source du phénomène", "polarity": "affirmative",
     "stem": "Sur un dériveur léger de sport, comment nomme-t-on couramment le chavirage et quelle en est la nature ?",
     "choices": [("Le « dessalage » : il est courant et sans gravité", True),
                 ("Le « naufrage » : il entraîne presque toujours la perte du bateau", False),
                 ("L’« auloffée » : elle ne survient qu’au près serré", False)],
     "explanation": "Sur un dériveur léger, le chavirage — dit dessalage — est courant et sans gravité ; il vient d’une recherche excessive de vitesse ou d’un mauvais placement des équipiers."},
    {"ref": "Voile — Foc : Présentation", "polarity": "affirmative",
     "stem": "Qu’est-ce que le foc sur un voilier ?",
     "choices": [("Une voile d’avant de forme triangulaire, retenue à l’étai par son guindant", True),
                 ("La voile principale gréée en arrière du mât", False),
                 ("Un câble du gréement dormant qui maintient le mât", False)],
     "explanation": "Le foc est une voile d’avant triangulaire retenue à l’étai par son guindant ; il joue un rôle primordial dans la réussite du virement de bord."},

    # --- Voile (DE) — aus dem deutschen Wikipedia (CC BY-SA) -----------------
    {"ref": "Voile — Kurse zum Wind : Im Wind", "polarity": "affirmative", "lang": "de",
     "stem": "Was geschieht, wenn ein Segelboot den kleinstmöglichen segelbaren Winkel zum Wind unterschreitet?",
     "choices": [("Es wird kein Vortrieb mehr erzeugt und die Segel killen (flattern)", True),
                 ("Das Boot erreicht vor dem Wind seine Höchstgeschwindigkeit", False),
                 ("Es wird automatisch eine Patenthalse ausgelöst", False)],
     "explanation": "Im Wind-Sektor wird kein Vortrieb mehr erzeugt, die Segel killen; das Ziel kann nur durch Kreuzen angelaufen werden."},
    {"ref": "Voile — Halse : Présentation", "polarity": "affirmative", "lang": "de",
     "stem": "Wodurch unterscheidet sich die Halse von der Wende?",
     "choices": [("Bei der Halse geht das Fahrzeug mit dem Heck durch den Wind", True),
                 ("Bei der Halse geht das Fahrzeug mit dem Bug durch den Wind", False),
                 ("Die Halse ist immer ohne Kursänderung möglich", False)],
     "explanation": "Bei der Halse geht das Boot mit dem Heck durch den Wind (die Wende mit dem Bug); unsauber ausgeführt droht eine Patenthalse, bei der der Großbaum unkontrolliert umschlägt."},
    {"ref": "Voile — Wende (Segeln) : Présentation", "polarity": "affirmative", "lang": "de",
     "stem": "Was kennzeichnet die Wende beim Segeln?",
     "choices": [("Das Schiff geht mit dem Bug durch den Wind; der Wind kommt kurzzeitig von vorne", True),
                 ("Das Schiff geht mit dem Heck durch den Wind", False),
                 ("Der Kurs bleibt während des Manövers unverändert", False)],
     "explanation": "Bei der Wende erfolgt ein Kurswechsel, bei dem das Schiff mit dem Bug durch den Wind geht (Wind kurzzeitig von vorne); die Halse geht mit dem Heck durch den Wind."},
    {"ref": "Voile — Spinnaker : Gefahren mit dem Spinnaker", "polarity": "affirmative", "lang": "de",
     "stem": "Was muss die Crew tun, wenn der Spinnaker das Boot außer Kontrolle zu bringen droht?",
     "choices": [("Sofort die Spinnakerschoten loswerfen, um den Druck zu reduzieren", True),
                 ("Einen Achtknoten in die Spinnakerschoten stecken", False),
                 ("Das Ruder hart anluven und den Kurs halten", False)],
     "explanation": "Bei drohendem Kontrollverlust (Querschlagen/Sonnenschuss) müssen die Spinnakerschoten sofort losgeworfen werden, um den Druck zu reduzieren; deshalb werden keine Achtknoten in diese Schoten gesteckt."},
    {"ref": "Voile — Kreuzen (Segeln) : Wie man gegen den Wind segeln kann", "polarity": "affirmative", "lang": "de",
     "stem": "Worauf beruht im Wesentlichen der Vortrieb beim Segeln gegen den Wind (Am-Wind-Kurs)?",
     "choices": [("Auf dem Tragflächeneffekt, ähnlich wie bei den Tragflächen eines Flugzeugs", True),
                 ("Allein auf dem Widerstand des Windes auf die Segel", False),
                 ("Auf dem Rückstoß des am Segel vorbeiströmenden Windes", False)],
     "explanation": "Gegen den Wind wirkt vor allem der Tragflächeneffekt (wie bei einem Flugzeugflügel); der quer zum Segel stehende Kraftanteil erzeugt zugleich Krängung und Abdrift."},

    # --- Voile (IT) — dal Wikipedia italiano (CC BY-SA) ----------------------
    {"ref": "Voile — Andatura (vela) : Présentation", "polarity": "affirmative", "lang": "it",
     "stem": "Che cosa si definisce «andatura» nella navigazione a vela?",
     "choices": [("I diversi modi di avanzare di un’imbarcazione a vela rispetto alla direzione del vento", True),
                 ("Un segnale di precedenza tra due imbarcazioni", False),
                 ("La manovra di cambio delle mure passando con la poppa nel vento", False)],
     "explanation": "Le andature sono i diversi modi di avanzare di una barca a vela rispetto alla direzione del vento; la propulsione è analoga alla portanza di un’ala."},
    {"ref": "Voile — Virata (nautica) : Présentation", "polarity": "affirmative", "lang": "it",
     "stem": "Come si effettua la virata (di prua)?",
     "choices": [("Portando la prua in direzione del vento, fino al cambio delle mure (da bolina a bolina)", True),
                 ("Portando la poppa attraverso il vento (fil di ruota)", False),
                 ("Mantenendo le stesse mure per tutta la manovra", False)],
     "explanation": "La virata cambia direzione portando la prua nel vento (da bolina a bolina); la manovra opposta, con la poppa nel vento, è l’abbattuta."},
    {"ref": "Voile — Abbattuta : Présentation", "polarity": "affirmative", "lang": "it",
     "stem": "Che cos’è l’abbattuta (virata in poppa)?",
     "choices": [("La manovra che cambia le mure passando con la poppa attraverso il fil di ruota", True),
                 ("La manovra di cambio mure portando la prua nel vento", False),
                 ("Una vela triangolare di prua issata alle andature portanti", False)],
     "explanation": "L’abbattuta cambia le mure passando con la poppa attraverso il fil di ruota; se involontaria e incontrollata si chiama strambata."},
    {"ref": "Voile — Bolina : Présentation", "polarity": "affirmative", "lang": "it",
     "stem": "Che cos’è l’andatura di bolina?",
     "choices": [("Un’andatura che consente di risalire il vento, con un angolo rispetto al vento reale tra circa 60° e 37°", True),
                 ("L’andatura in cui il vento proviene esattamente da poppa", False),
                 ("La manovra di cambio mure attraverso il fil di ruota", False)],
     "explanation": "La bolina permette di risalire il vento mantenendo un angolo rispetto al vento reale di circa 60°–37° (variabile secondo l’imbarcazione)."},
    {"ref": "Voile — Fiocco (vela) : Caratteristiche", "polarity": "affirmative", "lang": "it",
     "stem": "A che cosa serve il fiocco in un armo a sloop?",
     "choices": [("A mantenere il controllo della prua e a contribuire a bordeggiare (risalire il vento)", True),
                 ("A frenare l’imbarcazione nelle andature portanti", False),
                 ("A sostituire la randa nelle andature di poppa", False)],
     "explanation": "Nell’armo a sloop il fiocco (vela triangolare di prua, inserita su uno strallo) aiuta a controllare la prua e a bordeggiare/risalire il vento."},
]
